name: Deploy Discord Bot

on:
  push:
    branches:
      - main  # Срабатывает при пуше в основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest  # Среда для выполнения действий

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Клонируем репозиторий

    - name: Set up Python
      uses: actions/setup-python@v4  # Настроим Python
      with:
        python-version: '3.9'  # Укажите версию Python, которую используете

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt

    - name: Set up Discord bot token
      run: echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> $GITHUB_ENV  # Используем секретный токен

    - name: Run bot
      run: python bot.py  # Запускаем бота (замените на имя вашего скрипта)
